server:
  port: 9898

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
#    password: Hzs121914.
    password: hzs121914
#    url: jdbc:mysql://47.103.4.57:3306/hzsshopping?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    url: jdbc:mysql://localhost:3306/hzsshopping?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5 #最小连接数
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true #此属性控制从池返回的连接的默认自动提交行为,默认值：true
  ## QQ邮箱配置
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1219148123@qq.com #发送邮件的邮箱地址
    password:  isooniccvyjjhifb #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 1219148123@qq.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.hzs.rc.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

aliyun:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI4FsdA4yyr4DEJPHnasoY
  accessKeySecret: BZqg8ZanUovrxK5NkPEz3GY0zhS7ZP
  bucketName: hzsfile
  urlPrefix: hzsfile.oss-cn-beijing.aliyuncs.com

#logging:
#  file: hzs.log
#  level:
#    root: info
#  life:
#      hzs:
#        rc:
#          mapper: debug



